// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: GetFeedsByURLS.sql

package database

import (
	"context"
)

const getFeedsByURLS = `-- name: GetFeedsByURLS :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedsByURLS(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedsByURLS, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
